### PR TITLE
Give the container a name so other containers can link to it

### PR DESCRIPTION
**Pull request by RickMohr**

### CODE REVIEW

**Comment by RickMohr** [comment]
A downside of this change is that the proxy can no longer be tested with `awscli`, which doesn't appear to allow generating "virtual-hosted-style" URLs.

**Comment by RickMohr** [comment]
@hectcastro, OK to merge this?

**Comment by hectcastro** [comment]
👍

**Comment by RickMohr** [comment]
@hectcastro, thanks. I seem to lack merge permission on this repo.

**Comment by hectcastro** [comment]
Should be fixed now.

**Pull request merged**
